<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Synaptrix.Core\Synaptrix.Core.csproj" />
    <ProjectReference Include="..\..\src\Synaptrix.Generator\Synaptrix.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="..\..\src\Synaptrix.Generator\build\Synaptrix.Generator.targets" />

</Project>
